name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        node: [14, 16, 18]
        os:
          - name: darwin
            architecture: x86-64
            host: macos-10.15

          - name: linux
            architecture: x86-64
            host: ubuntu-latest

    name: ${{ matrix.os.name }}-${{ matrix.node.architecture }}-node${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: |
          npm ci
          ./scripts/setup.sh --config local.env
          source local.env
          make release
          npm test

  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: darwin
            architecture: x86-64
            host: macos-10.15

          - name: linux
            architecture: x86-64
            host: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build
        run: |
          ./scripts/setup.sh --config local.env
          source local.env
          make release

      - name: Prebuildify ${{ matrix.os.name }}-${{ matrix.os.architecture }}
        run: npm run prebuildify -- --platform=${{ matrix.os.name }} --arch=x64

      # Upload the end-user binary artifact
      - uses: actions/upload-artifact@v3
        with:
          name: prebuilt-binaries
          path: prebuilds
          retention-days: 1

  publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Upload the end-user binary artifact
      - uses: actions/download-artifact@v3
        run: ls -R
        working-directory: prebuilds
        
      - name: Check directories
        run: ls -R prebuilds
