name: PR Trigger

on:
  pull_request:
    branches: [rafaykhan/testing-prebuildify]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo ${{ github.event.pull_request }}

